version: '2'
services:
  eureka:
    image: ag/ace-center
    ports:
      - "8761:8761"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/var/lib/redis
